### ISSUE TITLE
iOS : Bugfender SDK update is failing 

### ISSUE THREAD

**Issue by chetanbansal019** [bugfender/cordova-plugin-bugfender#10]
Hi Team,

As per the instructions mentioned to update the iOS Bugfender SDK, when i am trying to run "pod install", the update is failing with the following error
![Screen Shot 2020-06-19 at 2 19 40 PM](https://user-images.githubusercontent.com/28653223/85114858-5e67e000-b238-11ea-8ffe-4c67dbd80f66.png)

I am setting up the SDK on Ionic 4 Capacitor 2.2 application. Although i can see the logs and it works brilliantly. Was trying to update the iOS SDK anyways.
I think this will require an update in the plugin to update the dependency versions..

Let me know if any additional details are required from my end.

**Comment by jgimenez** [comment]
Hi @chetanbansal019, that's right, the SDK does not offer an ObjC target anymore, we'll have to update the dependency. Thanks for sharing this.

**Comment by chetanbansal019** [comment]
Awesome.. Thanks for the response... 👍

**Comment by jgimenez** [comment]
Question: which instructions were you following? I can't find any instructions to update in the SDK README

**Comment by chetanbansal019** [comment]
https://github.com/bugfender/BugfenderSDK-iOS#using-cocoapods
I tried the step that were their for iOS installation.. But i get it, that should not be required to while working with ionic SDK.
I saw these instructions in the dashboard as well.. With a ! mark above ios native.

**Comment by jgimenez** [comment]
Thanks, those instructions are meant for people who use the SDKs directly in a native application. Sometimes the adapting SDKs like this one need some additional changes.

An update was just published, version 2.0.1, updating to the latest version of both iOS and Android SDKs.
