### ISSUE TITLE
can you please share a sample project that uses the Cordova plugin?

### ISSUE THREAD

**Issue by billylo1** [bugfender/cordova-plugin-bugfender#2]
I followed the instructions here, but no luck.  Bugfender.log is not visible to my javascript code.  Tried adding the js files into www and added bugfender.js and require.js to my project.  Still no luck.  Could use some help here.  

thanks,

**Comment by jgimenez** [comment]
You can generate a sample project with the following commands:

```
cordova create bugfender-test
cordova plugin add cordova-plugin-bugfender --variable BUGFENDER_APP_KEY=XXX --save
cordova platform add ios
cordova build ios
cordova platform add android
cordova build android
```

I would recommend reading the console logs when adding the plugin or adding the platform. Both can reveal important information on why the installation didn't work. If you still have problems, please contact us at support and paste the full logs of the plugin installation, so we can assist you.
