### ISSUE TITLE
How to import

### ISSUE THREAD

**Issue by swoopyy** [bugfender/cordova-plugin-bugfender#3]
How to import this? Can't find it under @ionic-native in node modules after installation

**Comment by jgimenez** [comment]
Hi there, I would recommend you to check the README, you will find detailed instructions there

**Comment by swoopyy** [comment]
@jgimenez of course I read it :) But there is no description of how to import Bugfender and how the import statement should look like. Could you please update the readme with an import statement example?

**Comment by jgimenez** [comment]
That's great :) If you followed those instructions, Bugfender will be added to the global scope, no need for any import statements
