### ISSUE TITLE
Bugfender is undefined

### ISSUE THREAD

**Issue by 5Xtester** [bugfender/cordova-plugin-bugfender#4]
I integrated the Bugfender plugin for my cordova app as mentioned. But I get the error "bugfender is undefined". The error is logged in the logs sections in bugfender dashboard.

**Comment by jgimenez** [comment]
Hi @5Xtester , maybe you used the wrong case?  You should use `Bugfender` with capital letter

**Comment by 5Xtester** [comment]
Hi @jgimenez , I used it exactly as `Bugfender`, but still I get it undefined.

**Comment by jgimenez** [comment]
OK, then maybe try to uninstall and install again the plugin, paying attention to the log messages in case there's something relevant there. It often happens that if a plugin installation goes wrong, Cordova still completes it but it doesn't work properly.

If after that still doesn't work, best would be that you post an example code where it doesn't work, so the problem can be reproduced. You can post it here or contact us via support.

**Comment by jgimenez** [comment]
Hi @5Xtester are you using Typescript? Bugfender is declared in Javascript as a global object, but Typescript requires you declare it explicitly. You can do this:

`declare var Bugfender: any;`
