### ISSUE TITLE
IOS: fatal error on 1.3.0 version

### ISSUE THREAD

**Issue by bitvalser** [bugfender/cordova-plugin-bugfender#8]
After update to last version (1.3.0)
IOS deploy build crashed

fatal error: 'BugfenderSDK/BugfenderSDK.h' file not found
#import <BugfenderSDK/BugfenderSDK.h>

After downgrade to 1.2.1 all work fine.

**Comment by jgimenez** [comment]
Hi there, which Cordova version are you using?

**Comment by bitvalser** [comment]
> Hi there, which Cordova version are you using?

8.1.2

**Comment by jgimenez** [comment]
OK, found the issue then! This plugin only supports Cordova 9 and up, you'll need to upgrade Cordova
